on: [push, pull_request]
name: Test
jobs:
  test:
    runs-on:
      - macos-latest
      - windows-latest
    steps:
      - name: Install
        uses: actions/setup-go@v2
        with:
          go-version: 1.18.x
      - name: Checkout
        uses: actions/checkout@v2
      - name: Test
        run: make build
